name: Artifact Workflow

on: [push]

env:
  ARTIFACT_NAME: testartifact

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Upload action
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: .
  
