name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    run-on: Ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: sarvinshrivastava/generator-repo@main
